"""
E₀ Canon Exposition Test
=========================
Empirical falsification: If the canon is correctly materialized as landscape,
an LLM receiving ONLY the framework's self-description should reflect the
canonical insights — without ever seeing the raw canon texts.

Usage:
    # Print the exact prompt (no API key needed):
    py -3 -m e0_controller.demo_canon_exposition --dry-run

    # Run against an LLM (requires OPENAI_API_KEY):
    py -3 -m e0_controller.demo_canon_exposition

    # Enriched mode with Self-Graph (Option B):
    py -3 -m e0_controller.demo_canon_exposition --self-graph

    # Or provide API key directly:
    py -3 -m e0_controller.demo_canon_exposition --api-key sk-...
"""

import argparse
import sys
from textwrap import dedent

from .canon_loader import load_canon, format_canon_summary
from .canon_self_bridge import build_self_exposition
from .controller import E0Controller
from .primitives import Outcome
from .self_graph import SelfGraph, active_components


# ──────────────────────────────────────────────
# Exposition Prompt
# ──────────────────────────────────────────────

EXPOSITION_SYSTEM = """\
You are a reasoning system. You receive a structured description of
a conceptual landscape — nodes, edges, derivation levels, and goal states.

Your task: analyze ONLY what is given to you. Do not reference external
knowledge. Treat the landscape description as your sole source of truth."""

EXPOSITION_USER = """\
Below is a self-description generated by a framework about its own
foundational concepts. The framework produced this from its internal
structure — a navigable graph of nodes and edges with derivation levels,
confidence gradients, and a goal state.

--- BEGIN FRAMEWORK SELF-DESCRIPTION ---
{summary}
--- END FRAMEWORK SELF-DESCRIPTION ---

Additionally, the framework navigated its own landscape from the root
concept to the goal. Here is the trace:

--- BEGIN NAVIGATION TRACE ---
{trace}
--- END NAVIGATION TRACE ---

Based on ONLY the information above, answer these questions:

1. What is this framework fundamentally about? Describe its core thesis
   in 2-3 sentences.

2. What role does "historisierung" (historization) play in this system?
   Why does it appear so centrally connected?

3. The shortest path from root to goal skips the physical concepts
   (zustand, masse, raumzeit) entirely. What does this imply about
   the framework's claims?

4. The confidence gradient drops from 0.9 (primitives) to 0.4 (thesis).
   What epistemological stance does this encode?

5. There are three structural dead-ends (traps): masse, raumzeit,
   strukturelle_zulaessigkeit. What do these traps tell you about
   the framework's architecture?

6. The edge from raumzeit back to historisierung has the highest
   effective tension (s_eff ≈ 5.0) in the entire navigation.
   What structural meaning does this carry?

Respond thoughtfully. No JSON. Free-form analysis."""


EXPOSITION_SELF_GRAPH_USER = """\
Below is a complete self-exposition generated by a framework. It contains:
1. What the framework BELIEVES (its canonical landscape of concepts)
2. How the framework OPERATES (its self-graph — operational component metrics)
3. A mapping showing which beliefs are operationally instantiated
4. An epistemic frontier: concepts it understands but cannot yet verify

The framework produced ALL of this from its own internal structure.
No external knowledge was provided.

--- BEGIN SELF-EXPOSITION ---
{exposition}
--- END SELF-EXPOSITION ---

Additionally, the framework navigated its own canonical landscape from
the root concept to the goal. During this navigation, it tracked its
operational components via the self-graph:

--- BEGIN NAVIGATION TRACE ---
{trace}
--- END NAVIGATION TRACE ---

Based on ONLY the information above, answer these questions:

1. What is the relationship between the framework's BELIEFS (canon)
   and its OPERATIONS (self-graph)? Are they the same structure seen
   from two sides, or genuinely separate?

2. The framework identifies an "epistemic frontier" — concepts it
   understands theoretically but cannot verify through experience.
   What does this frontier tell you about the framework's self-awareness?

3. The self-graph component "historization" maps directly to the canon
   primitive "historisierung". What is the significance of this identity?
   Why is it not merely an analogy?

4. Which canon concepts have NO operational counterpart? What would it
   mean for the framework to "operationalize" reflexivity or negative
   necessity? Is that even possible?

5. The Canon Coverage is not 100%. Is this a limitation or a feature?
   Should a framework be able to fully instantiate its own foundations?

6. The framework's self-graph uses rho=1.0 (cumulative, never decaying)
   while domain graphs typically use rho=0.9 (decaying). What does this
   asymmetry mean for self-knowledge vs. domain knowledge?

Respond thoughtfully. No JSON. Free-form analysis."""


# ──────────────────────────────────────────────
# Navigation Trace Generator
# ──────────────────────────────────────────────

def generate_trace() -> str:
    """Navigate the canon and produce a human-readable trace."""
    cl = load_canon("ontodynamics")
    ctrl = E0Controller(cl.landscape, lambda s, t: Outcome.SUCCESS)

    lines = []
    current = "differenz"
    goal = "negative_notwendigkeit"

    for step in range(20):
        r = ctrl.cycle(current)
        if r is None:
            lines.append(f"Step {step+1}: STUCK at {current}")
            break

        n_cands = len(r.candidates)
        lines.append(
            f"Step {step+1}: {r.source} -> {r.target}"
            f"  (s_eff={r.s_eff:.4f}, candidates={n_cands})"
        )
        current = r.target
        if current == goal:
            lines.append(f"GOAL REACHED in {step+1} steps.")
            break

    return "\n".join(lines)


# ──────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="E₀ Canon Exposition Test")
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print the prompt without calling an LLM.",
    )
    parser.add_argument(
        "--self-graph", action="store_true",
        help="Enriched mode: include Self-Graph operational data.",
    )
    parser.add_argument(
        "--api-key", type=str, default=None,
        help="OpenAI API key (or set OPENAI_API_KEY env var).",
    )
    parser.add_argument(
        "--model", type=str, default="gpt-4o",
        help="Model to use for the exposition test.",
    )
    args = parser.parse_args()

    # Build context
    cl = load_canon("ontodynamics")

    if args.self_graph:
        # Enriched mode: run controller with self-graph attached
        sg = SelfGraph()
        ctrl = E0Controller(cl.landscape, lambda s, t: Outcome.SUCCESS)
        ctrl.self_graph = sg

        # Navigate to accumulate operational data
        current = "differenz"
        trace_lines = []
        for step in range(20):
            r = ctrl.cycle(current)
            if r is None:
                trace_lines.append(f"Step {step+1}: STUCK at {current}")
                break
            n_cands = len(r.candidates)
            trace_lines.append(
                f"Step {step+1}: {r.source} -> {r.target}"
                f"  (s_eff={r.s_eff:.4f}, candidates={n_cands})"
            )
            current = r.target
            if current == "negative_notwendigkeit":
                trace_lines.append(f"GOAL REACHED in {step+1} steps.")
                break
        trace = "\n".join(trace_lines)

        exposition = build_self_exposition(cl, sg)
        system = EXPOSITION_SYSTEM
        user = EXPOSITION_SELF_GRAPH_USER.format(exposition=exposition, trace=trace)
    else:
        # Basic mode: canon summary only
        summary = format_canon_summary(cl.info)
        trace = generate_trace()
        system = EXPOSITION_SYSTEM
        user = EXPOSITION_USER.format(summary=summary, trace=trace)

    if args.dry_run:
        print("=" * 72)
        print("SYSTEM PROMPT:")
        print("=" * 72)
        print(system)
        print()
        print("=" * 72)
        print("USER PROMPT:")
        print("=" * 72)
        print(user)
        print()
        print("=" * 72)
        print(f"Total length: {len(system) + len(user)} chars")
        print("=" * 72)
        return

    # Live LLM call
    from .llm_adapter import LLMConfig, openai_call

    config = LLMConfig(
        model=args.model,
        temperature=0.3,
        max_tokens=2048,
        api_key=args.api_key,
    )

    print("Sending exposition prompt to LLM...")
    print(f"  Model: {config.model}")
    print(f"  Mode: {'self-graph enriched' if args.self_graph else 'canon only'}")
    print(f"  Prompt length: {len(system) + len(user)} chars")
    print()

    response = openai_call(system, user, config)

    print("=" * 72)
    print("LLM REFLECTION:")
    print("=" * 72)
    print(response)
    print("=" * 72)


if __name__ == "__main__":
    main()
